TERMS_HTML = r"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terms of Service - AI Video Bot</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            color: #333;
            background: #f5f5f5;
        }
        .container {
            max-width: 900px;
            margin: 0 auto;
            padding: 40px 20px;
            background: white;
            min-height: 100vh;
        }
        h1 {
            color: #1a1a1a;
            margin-bottom: 10px;
            font-size: 2.5em;
        }
        .last-updated {
            color: #666;
            margin-bottom: 30px;
            font-size: 0.9em;
        }
        h2 {
            color: #2c3e50;
            margin-top: 30px;
            margin-bottom: 15px;
            font-size: 1.5em;
            border-bottom: 2px solid #3498db;
            padding-bottom: 5px;
        }
        p {
            margin-bottom: 15px;
            color: #555;
        }
        ul {
            margin-left: 20px;
            margin-bottom: 15px;
        }
        li {
            margin-bottom: 8px;
            color: #555;
        }
        .back-link {
            display: inline-block;
            margin-top: 30px;
            color: #3498db;
            text-decoration: none;
            font-weight: 500;
        }
        .back-link:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Terms of Service</h1>
        <p class="last-updated">Last Updated: December 25, 2024</p>

        <h2>1. Acceptance of Terms</h2>
        <p>By accessing and using AI Video Bot ("the Service"), you accept and agree to be bound by the terms and provisions of this agreement. If you do not agree to these terms, please do not use the Service.</p>

        <h2>2. Description of Service</h2>
        <p>AI Video Bot is an automated video generation and social media publishing platform that allows users to:</p>
        <ul>
            <li>Generate AI-powered short-form videos</li>
            <li>Connect social media accounts (TikTok, Instagram, YouTube)</li>
            <li>Automatically publish videos to connected platforms</li>
            <li>Manage video series and content schedules</li>
        </ul>

        <h2>3. User Accounts and Social Media Authorization</h2>
        <p>To use the Service, you must:</p>
        <ul>
            <li>Provide accurate and complete registration information</li>
            <li>Maintain the security of your account credentials</li>
            <li>Authorize our application to post content on your behalf to connected social media platforms</li>
            <li>Ensure you have the legal right to authorize such posting</li>
        </ul>
        <p>You are responsible for all activities that occur under your account and all content posted to your social media accounts through our Service.</p>

        <h2>4. Content and Intellectual Property</h2>
        <p><strong>User-Generated Content:</strong></p>
        <ul>
            <li>You retain ownership of videos and content you create using the Service</li>
            <li>You grant us a license to process, store, and publish your content to your connected social media accounts</li>
            <li>You represent that you have all necessary rights to any content you provide</li>
        </ul>
        <p><strong>AI-Generated Content:</strong></p>
        <ul>
            <li>Videos generated by our AI are created based on your inputs and preferences</li>
            <li>You are responsible for reviewing content before it is published</li>
            <li>We do not claim ownership of AI-generated content created through the Service</li>
        </ul>

        <h2>5. Social Media Platform Compliance</h2>
        <p>By using our Service to publish to social media platforms, you agree to:</p>
        <ul>
            <li>Comply with all terms of service of TikTok, Instagram, YouTube, and other connected platforms</li>
            <li>Not use the Service to post prohibited, harmful, or illegal content</li>
            <li>Not violate any community guidelines or content policies of connected platforms</li>
            <li>Accept that platform-specific content restrictions and rate limits apply</li>
        </ul>

        <h2>6. Prohibited Uses</h2>
        <p>You may not use the Service to:</p>
        <ul>
            <li>Post spam, misleading, or deceptive content</li>
            <li>Violate any laws or regulations</li>
            <li>Infringe on intellectual property rights of others</li>
            <li>Post hateful, abusive, or harassing content</li>
            <li>Distribute malware or engage in hacking activities</li>
            <li>Abuse or exploit minors in any way</li>
            <li>Impersonate others or misrepresent your affiliation</li>
        </ul>

        <h2>7. Service Availability and Modifications</h2>
        <p>We reserve the right to:</p>
        <ul>
            <li>Modify or discontinue the Service at any time</li>
            <li>Refuse service to anyone for any reason</li>
            <li>Remove or disable content that violates these terms</li>
            <li>Suspend or terminate accounts that breach these terms</li>
        </ul>
        <p>The Service is provided "as is" without warranties of any kind. We do not guarantee uninterrupted or error-free operation.</p>

        <h2>8. Limitation of Liability</h2>
        <p>To the maximum extent permitted by law:</p>
        <ul>
            <li>We are not liable for any indirect, incidental, or consequential damages</li>
            <li>We are not responsible for content posted to your social media accounts</li>
            <li>We are not liable for actions taken by social media platforms against your accounts</li>
            <li>Our total liability shall not exceed the amount you paid for the Service</li>
        </ul>

        <h2>9. Privacy and Data Protection</h2>
        <p>Your use of the Service is also governed by our Privacy Policy. We collect and process data as described in the Privacy Policy, including:</p>
        <ul>
            <li>Account information and credentials</li>
            <li>Social media access tokens (stored securely)</li>
            <li>Video content and metadata</li>
            <li>Usage analytics and logs</li>
        </ul>

        <h2>10. Third-Party Services</h2>
        <p>The Service integrates with third-party platforms (TikTok, Instagram, YouTube). We are not responsible for:</p>
        <ul>
            <li>The availability or performance of third-party services</li>
            <li>Changes to third-party APIs or terms of service</li>
            <li>Actions taken by third-party platforms</li>
        </ul>

        <h2>11. Termination</h2>
        <p>You may terminate your account at any time by:</p>
        <ul>
            <li>Disconnecting all social media accounts</li>
            <li>Deleting your account through the Service</li>
            <li>Contacting our support team</li>
        </ul>
        <p>We may terminate or suspend your account immediately if you breach these terms.</p>

        <h2>12. Changes to Terms</h2>
        <p>We may update these Terms of Service from time to time. Continued use of the Service after changes constitutes acceptance of the modified terms. We will notify users of significant changes via email or in-app notification.</p>

        <h2>13. Governing Law</h2>
        <p>These terms shall be governed by and construed in accordance with applicable laws. Any disputes shall be resolved through binding arbitration.</p>

        <h2>14. Contact Information</h2>
        <p>If you have questions about these Terms of Service, please contact us at:</p>
        <p>Email: support@aivideobot.com</p>

        <a href="/" class="back-link">← Back to Home</a>
    </div>
</body>
</html>
"""

PRIVACY_HTML = r"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Privacy Policy - AI Video Bot</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            color: #333;
            background: #f5f5f5;
        }
        .container {
            max-width: 900px;
            margin: 0 auto;
            padding: 40px 20px;
            background: white;
            min-height: 100vh;
        }
        h1 {
            color: #1a1a1a;
            margin-bottom: 10px;
            font-size: 2.5em;
        }
        .last-updated {
            color: #666;
            margin-bottom: 30px;
            font-size: 0.9em;
        }
        h2 {
            color: #2c3e50;
            margin-top: 30px;
            margin-bottom: 15px;
            font-size: 1.5em;
            border-bottom: 2px solid #3498db;
            padding-bottom: 5px;
        }
        h3 {
            color: #34495e;
            margin-top: 20px;
            margin-bottom: 10px;
            font-size: 1.2em;
        }
        p {
            margin-bottom: 15px;
            color: #555;
        }
        ul {
            margin-left: 20px;
            margin-bottom: 15px;
        }
        li {
            margin-bottom: 8px;
            color: #555;
        }
        .highlight {
            background: #fff3cd;
            padding: 15px;
            border-left: 4px solid #ffc107;
            margin-bottom: 20px;
        }
        .back-link {
            display: inline-block;
            margin-top: 30px;
            color: #3498db;
            text-decoration: none;
            font-weight: 500;
        }
        .back-link:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Privacy Policy</h1>
        <p class="last-updated">Last Updated: December 25, 2024</p>

        <div class="highlight">
            <strong>Your Privacy Matters:</strong> This Privacy Policy explains how AI Video Bot collects, uses, stores, and protects your personal information when you use our service.
        </div>

        <h2>1. Information We Collect</h2>

        <h3>1.1 Account Information</h3>
        <p>When you create an account, we collect:</p>
        <ul>
            <li>Email address</li>
            <li>Username or display name</li>
            <li>Password (encrypted and securely stored)</li>
            <li>Account preferences and settings</li>
        </ul>

        <h3>1.2 Social Media Integration Data</h3>
        <p>When you connect social media accounts (TikTok, Instagram, YouTube), we collect and store:</p>
        <ul>
            <li><strong>OAuth Access Tokens:</strong> Securely encrypted tokens that allow us to post on your behalf</li>
            <li><strong>Refresh Tokens:</strong> To maintain connection without requiring repeated logins</li>
            <li><strong>Profile Information:</strong> Your username, profile ID, and avatar from connected platforms</li>
            <li><strong>Scope Permissions:</strong> Record of what permissions you've granted (e.g., video.upload)</li>
        </ul>

        <h3>1.3 Content and Usage Data</h3>
        <p>We collect information about how you use the Service:</p>
        <ul>
            <li>Video topics, scripts, and generated content</li>
            <li>Customization preferences (voice, art style, caption style, etc.)</li>
            <li>Upload history and publishing logs</li>
            <li>Series configurations and schedules</li>
            <li>API usage and error logs</li>
        </ul>

        <h3>1.4 Technical Data</h3>
        <ul>
            <li>IP address and geolocation (country/region)</li>
            <li>Device type and browser information</li>
            <li>Usage analytics and performance metrics</li>
            <li>Error reports and debugging logs</li>
        </ul>

        <h2>2. How We Use Your Information</h2>

        <h3>2.1 Core Service Functions</h3>
        <ul>
            <li><strong>Video Generation:</strong> Process your inputs to create AI-generated videos</li>
            <li><strong>Social Media Publishing:</strong> Use OAuth tokens to post videos to your connected accounts</li>
            <li><strong>Content Management:</strong> Store and organize your video series and schedules</li>
            <li><strong>Authentication:</strong> Verify your identity and maintain secure access</li>
        </ul>

        <h3>2.2 Service Improvement</h3>
        <ul>
            <li>Analyze usage patterns to improve features</li>
            <li>Debug errors and optimize performance</li>
            <li>Develop new features based on user needs</li>
            <li>Monitor system health and prevent abuse</li>
        </ul>

        <h3>2.3 Communication</h3>
        <ul>
            <li>Send service updates and important notifications</li>
            <li>Respond to support requests</li>
            <li>Notify about account activity or security issues</li>
            <li>Share product updates (with option to opt-out)</li>
        </ul>

        <h2>3. How We Store and Protect Your Data</h2>

        <h3>3.1 Data Storage</h3>
        <p>Your data is stored securely using:</p>
        <ul>
            <li><strong>Supabase (PostgreSQL):</strong> Account data, series configurations, and metadata</li>
            <li><strong>Supabase Storage:</strong> Generated videos and media files</li>
            <li><strong>Encrypted at Rest:</strong> All sensitive data encrypted in database</li>
            <li><strong>Encrypted in Transit:</strong> HTTPS/TLS for all data transmission</li>
        </ul>

        <h3>3.2 Security Measures</h3>
        <ul>
            <li>OAuth tokens encrypted with industry-standard encryption (AES-256)</li>
            <li>Passwords hashed using bcrypt with salt</li>
            <li>Regular security audits and vulnerability assessments</li>
            <li>Access controls and authentication for all API endpoints</li>
            <li>Rate limiting to prevent abuse and brute-force attacks</li>
        </ul>

        <h3>3.3 Data Retention</h3>
        <ul>
            <li>Account data retained while your account is active</li>
            <li>Generated videos stored according to your subscription plan</li>
            <li>Logs and analytics data retained for 90 days</li>
            <li>Upon account deletion, personal data removed within 30 days</li>
        </ul>

        <h2>4. Sharing Your Information</h2>

        <h3>4.1 Third-Party Services We Use</h3>
        <p>We share limited data with trusted third parties to provide the Service:</p>
        <ul>
            <li><strong>TikTok:</strong> Video files and metadata when you authorize posting</li>
            <li><strong>Instagram:</strong> Video URLs and captions when you authorize posting</li>
            <li><strong>YouTube:</strong> Video files and metadata when you authorize posting</li>
            <li><strong>OpenAI:</strong> Text prompts for script generation (no personal identifiers)</li>
            <li><strong>ElevenLabs:</strong> Text scripts for voice synthesis (no personal identifiers)</li>
            <li><strong>Supabase:</strong> Database and file storage provider</li>
            <li><strong>Stripe:</strong> Payment processing (if using paid features)</li>
        </ul>

        <h3>4.2 What We DON'T Share</h3>
        <ul>
            <li>We never sell your personal information to third parties</li>
            <li>We don't share your OAuth tokens with anyone</li>
            <li>We don't use your content for training AI models without permission</li>
            <li>We don't share analytics data that identifies individual users</li>
        </ul>

        <h3>4.3 Legal Requirements</h3>
        <p>We may disclose your information if required by law or to:</p>
        <ul>
            <li>Comply with legal processes or government requests</li>
            <li>Enforce our Terms of Service</li>
            <li>Protect rights, property, or safety of our users</li>
            <li>Investigate fraud or security issues</li>
        </ul>

        <h2>5. Your Rights and Choices</h2>

        <h3>5.1 Access and Control</h3>
        <p>You have the right to:</p>
        <ul>
            <li><strong>Access Your Data:</strong> Request a copy of all data we have about you</li>
            <li><strong>Update Information:</strong> Modify your account details and preferences</li>
            <li><strong>Delete Your Account:</strong> Permanently remove your account and associated data</li>
            <li><strong>Revoke OAuth Access:</strong> Disconnect social media accounts at any time</li>
            <li><strong>Export Your Content:</strong> Download videos you've created</li>
        </ul>

        <h3>5.2 Social Media Permissions</h3>
        <p>You can manage social media permissions by:</p>
        <ul>
            <li>Disconnecting accounts in your dashboard settings</li>
            <li>Revoking access directly in TikTok/Instagram/YouTube settings</li>
            <li>Choosing which platforms to publish to for each video series</li>
        </ul>

        <h3>5.3 Cookie Preferences</h3>
        <p>We use cookies for:</p>
        <ul>
            <li>Authentication and session management</li>
            <li>Remembering your preferences</li>
            <li>Analytics (can be disabled in settings)</li>
        </ul>

        <h2>6. Children's Privacy</h2>
        <p>Our Service is not intended for users under 13 years of age. We do not knowingly collect information from children under 13. If you believe we have collected data from a child, please contact us immediately.</p>

        <h2>7. International Data Transfers</h2>
        <p>Your data may be transferred to and processed in countries other than your own. We ensure appropriate safeguards are in place to protect your data in compliance with applicable privacy laws.</p>

        <h2>8. Changes to Privacy Policy</h2>
        <p>We may update this Privacy Policy to reflect changes in our practices or legal requirements. We will:</p>
        <ul>
            <li>Notify you via email of significant changes</li>
            <li>Post updates on our website with revision date</li>
            <li>Give you opportunity to review before continuing use</li>
        </ul>

        <h2>9. TikTok-Specific Privacy Information</h2>
        <p>When you connect your TikTok account:</p>
        <ul>
            <li>We request only the minimum permissions needed (user.info.basic, video.upload)</li>
            <li>We store your TikTok access token securely encrypted in our database</li>
            <li>We only access your TikTok account when you explicitly authorize video uploads</li>
            <li>We do not access your TikTok messages, followers, or other private data</li>
            <li>You can revoke our access anytime in TikTok Settings > Security and login > Apps</li>
        </ul>

        <h2>10. Instagram-Specific Privacy Information</h2>
        <p>When you connect your Instagram Business account:</p>
        <ul>
            <li>Requires linking to a Facebook Page (Instagram API requirement)</li>
            <li>We request instagram_basic and instagram_content_publish permissions</li>
            <li>We use long-lived tokens (60-day expiry) to maintain connection</li>
            <li>We only upload videos you explicitly authorize</li>
            <li>You can disconnect via Instagram Settings or Facebook App Settings</li>
        </ul>

        <h2>11. Contact Us</h2>
        <p>If you have questions about this Privacy Policy or how we handle your data:</p>
        <ul>
            <li><strong>Email:</strong> privacy@aivideobot.com</li>
            <li><strong>Support:</strong> support@aivideobot.com</li>
            <li><strong>Data Protection Requests:</strong> dpo@aivideobot.com</li>
        </ul>
        <p>We will respond to privacy inquiries within 30 days.</p>

        <h2>12. Your California Privacy Rights</h2>
        <p>If you are a California resident, you have additional rights under the California Consumer Privacy Act (CCPA):</p>
        <ul>
            <li>Right to know what personal information we collect and how it's used</li>
            <li>Right to request deletion of your personal information</li>
            <li>Right to opt-out of sale of personal information (we don't sell data)</li>
            <li>Right to non-discrimination for exercising privacy rights</li>
        </ul>

        <a href="/" class="back-link">← Back to Home</a>
    </div>
</body>
</html>
"""
